"""accounts and investment holdings, subcategory, insights cache

Revision ID: 85008d65fa70
Revises: d29b3fa9d081
Create Date: 2026-08-27 01:32:30.941570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85008d65fa70'
down_revision: Union[str, None] = 'd29b3fa9d081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('bank_name', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('account_tail', sa.Text(), nullable=True),
    sa.Column('opening_balance_paise', sa.BigInteger(), nullable=False),
    sa.Column('opening_balance_as_of', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("kind in ('BANK', 'CREDIT_CARD', 'WALLET', 'CASH', 'OTHER')", name='ck_accounts_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_account_tail', 'accounts', ['account_tail'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('units', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('avg_cost_paise', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('current_value_paise', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("kind in ('STOCK', 'MUTUAL_FUND', 'FD', 'GOLD', 'PPF', 'OTHER')", name='ck_holdings_kind'),
    sa.CheckConstraint('units is null or units >= 0', name='ck_holdings_units_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insights_cache',
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('from_ms', sa.BigInteger(), nullable=False),
    sa.Column('to_ms', sa.BigInteger(), nullable=False),
    sa.Column('stats_hash', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('period', 'from_ms', 'to_ms', 'stats_hash')
    )
    op.create_table('holding_transactions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('holding_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('units', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('price_paise', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('realized_gain_paise', sa.BigInteger(), nullable=True),
    sa.Column('occurred_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("type in ('BUY', 'SELL', 'VALUATION_UPDATE')", name='ck_holdingtxn_type'),
    sa.CheckConstraint('amount_paise >= 0', name='ck_holdingtxn_amount_nonneg'),
    sa.CheckConstraint('units is null or units > 0', name='ck_holdingtxn_units_positive'),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_holdingtxn_holding_occurred', 'holding_transactions', ['holding_id', 'occurred_at'], unique=False)
    op.add_column('transactions', sa.Column('account_id', sa.Text(), nullable=True))
    op.add_column('transactions', sa.Column('subcategory', sa.Text(), nullable=True))
    op.create_index('ix_txn_account_occurred', 'transactions', ['account_id', 'occurred_at'], unique=False)
    op.create_index('ix_txn_subcategory', 'transactions', ['subcategory'], unique=False, postgresql_where=sa.text('subcategory IS NOT NULL'))
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('ix_txn_subcategory', table_name='transactions', postgresql_where=sa.text('subcategory IS NOT NULL'))
    op.drop_index('ix_txn_account_occurred', table_name='transactions')
    op.drop_column('transactions', 'subcategory')
    op.drop_column('transactions', 'account_id')
    op.drop_index('ix_holdingtxn_holding_occurred', table_name='holding_transactions')
    op.drop_table('holding_transactions')
    op.drop_table('insights_cache')
    op.drop_table('holdings')
    op.drop_index('ix_accounts_account_tail', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
