"""initial schema

Revision ID: d29b3fa9d081
Revises: 
Create Date: 2026-08-27 00:42:57.884464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29b3fa9d081'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('last_seen_at', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("kind in ('phone','dashboard','agent')", name='ck_devices_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_categories',
    sa.Column('merchant_norm', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('merchant_norm')
    )
    op.create_table('transactions',
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.BigInteger(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('merchant_norm', sa.Text(), nullable=True),
    sa.Column('merchant_raw', sa.Text(), nullable=True),
    sa.Column('account_tail', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('balance_paise', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('category_source', sa.Text(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("category_source in ('USER', 'MEMORY', 'DASHBOARD', 'REMOTE', 'MODEL', 'SEED', 'NONE')", name='ck_txn_category_source'),
    sa.CheckConstraint("channel is null or channel in ('UPI', 'CARD', 'ATM', 'IMPS', 'NEFT', 'RTGS', 'NETBANKING', 'AUTOPAY', 'WALLET', 'UNKNOWN')", name='ck_txn_channel'),
    sa.CheckConstraint("direction in ('DEBIT', 'CREDIT')", name='ck_txn_direction'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index('ix_txn_device_updated', 'transactions', ['device_id', 'updated_at'], unique=False)
    op.create_index('ix_txn_merchant_norm', 'transactions', ['merchant_norm'], unique=False)
    op.create_index('ix_txn_needs_review', 'transactions', ['needs_review'], unique=False)
    op.create_index('ix_txn_occurred', 'transactions', ['occurred_at'], unique=False)
    op.create_index('ux_txn_reference', 'transactions', ['reference'], unique=True, postgresql_where=sa.text('reference IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_txn_reference', table_name='transactions', postgresql_where=sa.text('reference IS NOT NULL'))
    op.drop_index('ix_txn_occurred', table_name='transactions')
    op.drop_index('ix_txn_needs_review', table_name='transactions')
    op.drop_index('ix_txn_merchant_norm', table_name='transactions')
    op.drop_index('ix_txn_device_updated', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('merchant_categories')
    op.drop_table('devices')
    # ### end Alembic commands ###
