"""budget buckets, budget config, transaction import_seq

Revision ID: e8eb74ba17db
Revises: 85008d65fa70
Create Date: 2026-08-27 03:17:50.006566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8eb74ba17db'
down_revision: Union[str, None] = '85008d65fa70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_buckets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('monthly_target_paise', sa.BigInteger(), nullable=False),
    sa.Column('category_keys', sa.JSON(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("kind in ('spend','savings')", name='ck_budget_bucket_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_config',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('monthly_income_paise', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_budget_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('import_seq', sa.BigInteger(), nullable=True))
    op.drop_index('ix_txn_account_occurred', table_name='transactions')
    op.create_index('ix_txn_account_occurred', 'transactions', ['account_id', 'occurred_at', 'import_seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_txn_account_occurred', table_name='transactions')
    op.create_index('ix_txn_account_occurred', 'transactions', ['account_id', 'occurred_at'], unique=False)
    op.drop_column('transactions', 'import_seq')
    op.drop_table('budget_config')
    op.drop_table('budget_buckets')
    # ### end Alembic commands ###
